package kotlin.reflect.jvm.internal.impl.load.java.typeEnhancement;

import com.bitcoin.mwallet.BuildConfig;
import java.util.Map;
import kotlin.jvm.functions.Function1;
import kotlin.reflect.jvm.internal.impl.load.java.typeEnhancement.SignatureEnhancementBuilder.ClassEnhancementBuilder;
import kotlin.reflect.jvm.internal.impl.load.kotlin.SignatureBuildingComponents;
import org.bitcoinj.core.NetworkParameters;
import org.jetbrains.annotations.NotNull;

/* compiled from: predefinedEnhancementInfo.kt */
public final class PredefinedEnhancementInfoKt {
    /* access modifiers changed from: private */
    public static final JavaTypeQualifiers NOT_NULLABLE;
    /* access modifiers changed from: private */
    public static final JavaTypeQualifiers NOT_PLATFORM;
    /* access modifiers changed from: private */
    public static final JavaTypeQualifiers NULLABLE;
    @NotNull
    private static final Map<String, PredefinedFunctionEnhancementInfo> PREDEFINED_FUNCTION_ENHANCEMENT_INFO_BY_SIGNATURE;

    static {
        JavaTypeQualifiers javaTypeQualifiers = new JavaTypeQualifiers(NullabilityQualifier.NULLABLE, null, false, false, 8, null);
        NULLABLE = javaTypeQualifiers;
        JavaTypeQualifiers javaTypeQualifiers2 = new JavaTypeQualifiers(NullabilityQualifier.NOT_NULL, null, false, false, 8, null);
        NOT_PLATFORM = javaTypeQualifiers2;
        JavaTypeQualifiers javaTypeQualifiers3 = new JavaTypeQualifiers(NullabilityQualifier.NOT_NULL, null, true, false, 8, null);
        NOT_NULLABLE = javaTypeQualifiers3;
        SignatureBuildingComponents signatureBuildingComponents = SignatureBuildingComponents.INSTANCE;
        String javaLang = signatureBuildingComponents.javaLang("Object");
        String javaFunction = signatureBuildingComponents.javaFunction("Predicate");
        String javaFunction2 = signatureBuildingComponents.javaFunction("Function");
        String javaFunction3 = signatureBuildingComponents.javaFunction("Consumer");
        String javaFunction4 = signatureBuildingComponents.javaFunction("BiFunction");
        String javaFunction5 = signatureBuildingComponents.javaFunction("BiConsumer");
        String javaFunction6 = signatureBuildingComponents.javaFunction("UnaryOperator");
        String javaUtil = signatureBuildingComponents.javaUtil("stream/Stream");
        String javaUtil2 = signatureBuildingComponents.javaUtil("Optional");
        SignatureEnhancementBuilder signatureEnhancementBuilder = new SignatureEnhancementBuilder();
        String str = javaFunction3;
        String str2 = javaFunction;
        String str3 = javaUtil;
        String str4 = javaFunction;
        ClassEnhancementBuilder classEnhancementBuilder = new ClassEnhancementBuilder(signatureEnhancementBuilder, signatureBuildingComponents.javaUtil("Iterator"));
        String str5 = javaFunction6;
        String str6 = javaFunction6;
        SignatureEnhancementBuilder signatureEnhancementBuilder2 = signatureEnhancementBuilder;
        String str7 = javaFunction5;
        String str8 = javaUtil2;
        String str9 = javaFunction4;
        String str10 = javaFunction2;
        String str11 = str8;
        C2995xd5dbd441 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$1 = new C2995xd5dbd441(signatureBuildingComponents, str, str2, str3, str5, str7, javaLang, str9, str10, str11);
        classEnhancementBuilder.function("forEachRemaining", predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$1);
        SignatureBuildingComponents signatureBuildingComponents2 = signatureBuildingComponents;
        String str12 = str4;
        String str13 = str6;
        String str14 = javaFunction5;
        ClassEnhancementBuilder classEnhancementBuilder2 = new ClassEnhancementBuilder(signatureEnhancementBuilder2, signatureBuildingComponents.javaLang("Iterable"));
        String str15 = javaLang;
        C3006xd5dbd442 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$2 = new C3006xd5dbd442(signatureBuildingComponents2, str, str12, str3, str13, str7, str15, str9, str10, str11);
        classEnhancementBuilder2.function("spliterator", predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$2);
        ClassEnhancementBuilder classEnhancementBuilder3 = new ClassEnhancementBuilder(signatureEnhancementBuilder2, signatureBuildingComponents.javaUtil("Collection"));
        String str16 = str14;
        C3016xd5dbd443 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$3 = new C3016xd5dbd443(signatureBuildingComponents2, str, str12, str3, str13, str16, str15, str9, str10, str11);
        classEnhancementBuilder3.function("removeIf", predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$3);
        C3017xd5dbd444 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$4 = new C3017xd5dbd444(signatureBuildingComponents2, str, str12, str3, str13, str16, str15, str9, str10, str11);
        classEnhancementBuilder3.function("stream", predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$4);
        C3018xd5dbd445 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$5 = new C3018xd5dbd445(signatureBuildingComponents2, str, str12, str3, str13, str16, str15, str9, str10, str11);
        classEnhancementBuilder3.function("parallelStream", predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$5);
        ClassEnhancementBuilder classEnhancementBuilder4 = new ClassEnhancementBuilder(signatureEnhancementBuilder2, signatureBuildingComponents.javaUtil("List"));
        C3019xd5dbd446 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$6 = new C3019xd5dbd446(signatureBuildingComponents2, str, str12, str3, str13, str16, str15, str9, str10, str11);
        String str17 = "replaceAll";
        classEnhancementBuilder4.function(str17, predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$6);
        ClassEnhancementBuilder classEnhancementBuilder5 = new ClassEnhancementBuilder(signatureEnhancementBuilder2, signatureBuildingComponents.javaUtil("Map"));
        SignatureEnhancementBuilder signatureEnhancementBuilder3 = signatureEnhancementBuilder2;
        String str18 = str17;
        String str19 = javaLang;
        C3020xd5dbd447 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$7 = new C3020xd5dbd447(signatureBuildingComponents2, str, str12, str3, str13, str16, str19, str9, str10, str11);
        classEnhancementBuilder5.function("forEach", predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$7);
        C3021xd5dbd448 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$8 = new C3021xd5dbd448(signatureBuildingComponents2, str, str12, str3, str13, str16, str19, str9, str10, str11);
        classEnhancementBuilder5.function("putIfAbsent", predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$8);
        C3022xd5dbd449 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$9 = new C3022xd5dbd449(signatureBuildingComponents2, str, str12, str3, str13, str16, str19, str9, str10, str11);
        Function1 function1 = predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$9;
        String str20 = BuildConfig.FLAVOR;
        classEnhancementBuilder5.function(str20, function1);
        String str21 = str18;
        String str22 = str20;
        String str23 = javaLang;
        C2996xe59eb40f predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$10 = new C2996xe59eb40f(signatureBuildingComponents2, str, str12, str3, str13, str16, str23, str9, str10, str11);
        classEnhancementBuilder5.function(str22, predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$10);
        C2997xe59eb410 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$11 = new C2997xe59eb410(signatureBuildingComponents2, str, str12, str3, str13, str16, str23, str9, str10, str11);
        classEnhancementBuilder5.function(str21, predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$11);
        C2998xe59eb411 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$12 = new C2998xe59eb411(signatureBuildingComponents2, str, str12, str3, str13, str16, str23, str9, str10, str11);
        classEnhancementBuilder5.function("compute", predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$12);
        C2999xe59eb412 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$13 = new C2999xe59eb412(signatureBuildingComponents2, str, str12, str3, str13, str16, str23, str9, str10, str11);
        classEnhancementBuilder5.function("computeIfAbsent", predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$13);
        C3000xe59eb413 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$14 = new C3000xe59eb413(signatureBuildingComponents2, str, str12, str3, str13, str16, str23, str9, str10, str11);
        classEnhancementBuilder5.function("computeIfPresent", predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$14);
        C3001xe59eb414 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$15 = new C3001xe59eb414(signatureBuildingComponents2, str, str12, str3, str13, str16, str23, str9, str10, str11);
        classEnhancementBuilder5.function("merge", predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$15);
        String str24 = str8;
        SignatureEnhancementBuilder signatureEnhancementBuilder4 = signatureEnhancementBuilder3;
        ClassEnhancementBuilder classEnhancementBuilder6 = new ClassEnhancementBuilder(signatureEnhancementBuilder4, str24);
        String str25 = str24;
        C3002xe59eb415 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$16 = new C3002xe59eb415(signatureBuildingComponents2, str, str12, str3, str13, str16, str23, str9, str10, str25);
        classEnhancementBuilder6.function("empty", predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$16);
        C3003xe59eb416 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$17 = new C3003xe59eb416(signatureBuildingComponents, str, str12, str3, str13, str16, str23, str9, str10, str25);
        classEnhancementBuilder6.function("of", predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$17);
        C3004xe59eb417 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$18 = new C3004xe59eb417(signatureBuildingComponents, str, str12, str3, str13, str16, str23, str9, str10, str25);
        classEnhancementBuilder6.function("ofNullable", predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$18);
        SignatureBuildingComponents signatureBuildingComponents3 = signatureBuildingComponents;
        C3005xe59eb418 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$19 = new C3005xe59eb418(signatureBuildingComponents3, str, str12, str3, str13, str16, str23, str9, str10, str25);
        String str26 = "get";
        classEnhancementBuilder6.function(str26, predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$19);
        String str27 = str26;
        C3007xe59eb42e predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$20 = new C3007xe59eb42e(signatureBuildingComponents3, str, str12, str3, str13, str16, javaLang, str9, str10, str25);
        classEnhancementBuilder6.function("ifPresent", predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$20);
        SignatureBuildingComponents signatureBuildingComponents4 = signatureBuildingComponents;
        String str28 = javaFunction3;
        ClassEnhancementBuilder classEnhancementBuilder7 = new ClassEnhancementBuilder(signatureEnhancementBuilder4, signatureBuildingComponents.javaLang("ref/Reference"));
        C3008xe59eb42f predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$21 = new C3008xe59eb42f(signatureBuildingComponents4, str, str12, str3, str13, str16, javaLang, str9, str10, str25);
        String str29 = str27;
        classEnhancementBuilder7.function(str29, predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$21);
        String str30 = str4;
        ClassEnhancementBuilder classEnhancementBuilder8 = new ClassEnhancementBuilder(signatureEnhancementBuilder4, str30);
        String str31 = str28;
        String str32 = str30;
        String str33 = str29;
        C3009xe59eb430 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$22 = new C3009xe59eb430(signatureBuildingComponents4, str31, str32, str3, str13, str16, javaLang, str9, str10, str25);
        Function1 function12 = predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$22;
        String str34 = NetworkParameters.PAYMENT_PROTOCOL_ID_TESTNET;
        classEnhancementBuilder8.function(str34, function12);
        String str35 = str30;
        ClassEnhancementBuilder classEnhancementBuilder9 = new ClassEnhancementBuilder(signatureEnhancementBuilder4, signatureBuildingComponents.javaFunction("BiPredicate"));
        String str36 = str14;
        SignatureBuildingComponents signatureBuildingComponents5 = signatureBuildingComponents;
        String str37 = str34;
        String str38 = javaLang;
        C3010xe59eb431 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$23 = new C3010xe59eb431(signatureBuildingComponents4, str31, str32, str3, str13, str36, str38, str9, str10, str25);
        classEnhancementBuilder9.function(str37, predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$23);
        String str39 = str28;
        ClassEnhancementBuilder classEnhancementBuilder10 = new ClassEnhancementBuilder(signatureEnhancementBuilder4, str39);
        SignatureBuildingComponents signatureBuildingComponents6 = signatureBuildingComponents5;
        String str40 = str39;
        String str41 = str35;
        C3011xe59eb432 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$24 = new C3011xe59eb432(signatureBuildingComponents6, str40, str41, str3, str13, str36, str38, str9, str10, str25);
        String str42 = "accept";
        classEnhancementBuilder10.function(str42, predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$24);
        String str43 = str14;
        ClassEnhancementBuilder classEnhancementBuilder11 = new ClassEnhancementBuilder(signatureEnhancementBuilder4, str43);
        String str44 = str43;
        String str45 = str43;
        String str46 = str42;
        String str47 = javaLang;
        C3012xe59eb433 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$25 = new C3012xe59eb433(signatureBuildingComponents6, str40, str41, str3, str13, str44, str47, str9, str10, str25);
        classEnhancementBuilder11.function(str46, predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$25);
        ClassEnhancementBuilder classEnhancementBuilder12 = new ClassEnhancementBuilder(signatureEnhancementBuilder4, javaFunction2);
        String str48 = str45;
        C3013xe59eb434 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$26 = new C3013xe59eb434(signatureBuildingComponents6, str40, str41, str3, str13, str48, str47, str9, str10, str25);
        String str49 = "apply";
        classEnhancementBuilder12.function(str49, predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$26);
        ClassEnhancementBuilder classEnhancementBuilder13 = new ClassEnhancementBuilder(signatureEnhancementBuilder4, javaFunction4);
        String str50 = str39;
        String str51 = str49;
        String str52 = javaLang;
        C3014xe59eb435 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$27 = new C3014xe59eb435(signatureBuildingComponents6, str40, str41, str3, str13, str48, str52, str9, str10, str25);
        classEnhancementBuilder13.function(str51, predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$27);
        SignatureBuildingComponents signatureBuildingComponents7 = signatureBuildingComponents5;
        ClassEnhancementBuilder classEnhancementBuilder14 = new ClassEnhancementBuilder(signatureEnhancementBuilder4, signatureBuildingComponents7.javaFunction("Supplier"));
        C3015xe59eb436 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$28 = new C3015xe59eb436(signatureBuildingComponents7, str50, str41, str3, str13, str48, str52, str9, str10, str25);
        classEnhancementBuilder14.function(str33, predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$28);
        PREDEFINED_FUNCTION_ENHANCEMENT_INFO_BY_SIGNATURE = signatureEnhancementBuilder4.build();
    }

    @NotNull
    public static final Map<String, PredefinedFunctionEnhancementInfo> getPREDEFINED_FUNCTION_ENHANCEMENT_INFO_BY_SIGNATURE() {
        return PREDEFINED_FUNCTION_ENHANCEMENT_INFO_BY_SIGNATURE;
    }
}
